Update docker-image.yml

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -44,45 +44,37 @@ jobs:
             - name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3.3.0
 
-            # Step 4: Log in to Docker Hub using credentials stored in GitHub secrets
+            # Step 4: Extract the SEMVER version number from the release tag or take it as it comes from workflow dispatch
+            - name: Extract SEMVER
+              run: |
+                if [ "${{ github.event_name }}" = "release" ]; then
+                  if [[ "${{ github.event.release.tag_name }}" =~ ^flowise@([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
+                    echo "SEMVER=${BASH_REMATCH[1]}" >> $GITHUB_ENV
+                  else
+                    echo "Invalid release tag for automation. It should match the pattern 'flowise@X.Y.Z'." >&2
+                    exit 1
+                  fi
+                elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
+                  echo "SEMVER=${{ github.event.inputs.tag_version }}" >> $GITHUB_ENV
+                fi
+
+            # Step 5: Log in to Docker Hub using credentials stored in GitHub secrets
             - name: Login to Docker Hub
               uses: docker/login-action@v3.1.0
               with:
                   username: ${{ secrets.DOCKERHUB_USERNAME }}
                   password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-            # Step 5: Extract the SEMVER version number from the release tag (e.g., 'flowise@X.Y.Z') or take it as it comes from workflow dispatch.
-            - name: Extract SEMVER
-              id: extract_version
-              run: |
-                if [ "${{ github.event_name }}" = "release" ]; then
-                  if [[ "${{ github.event.release.tag_name }}" =~ ^flowise@([0-9]+\.[0-9]+\.[0-9]+)$ ]]; then
-                    echo "::set-output name=semver::${BASH_REMATCH[1]}"
-                  else
-                    echo "Invalid release tag for automation. It should match the pattern 'flowise@X.Y.Z'." >&2
-                    exit 1
-                  fi
-                elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
-                  echo "::set-output name=semver::${{ github.event.inputs.tag_version }}"
-                fi
-
             # Step 6: Build and push the Docker image to Docker Hub
             - name: Build and push
               uses: docker/build-push-action@v5.3.0
               with:
-                  # Path to the directory containing the Dockerfile
                   context: .
-                  # Path to the Dockerfile used for building the image
                   file: ./docker/Dockerfile
-                  # Build arguments passed to the Dockerfile (using the Node.js version specified)
                   build-args: |
                       NODE_VERSION=${{ github.event.inputs.node_version || '20' }}
-                  # Platforms to build the Docker image for
                   platforms: linux/amd64,linux/arm64
-                  # Push the built image to Docker Hub
                   push: true
-                  # Use the latest image tag for caching to optimize build times
                   cache-from: type=registry,ref=flowiseai/flowise:latest
                   cache-to: type=registry,ref=flowiseai/flowise:latest,mode=max
-                  # Tag the new image with the extracted SEMVER value
-                  tags: flowiseai/flowise:${{ steps.extract_version.outputs.semver }}
+                  tags: flowiseai/flowise:${{ env.SEMVER }}
